### ISSUE TITLE
Analysis report feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [furkanusta/Bilkent-CS319#1]
[8.analysis.pdf](https://github.com/furkanusta/Bilkent-CS319/files/182266/8.analysis.pdf)

**Comment by furkanusta** [comment]
https://github.com/furkanusta/Bilkent-CS319/commit/a74c558c7d02321ff41028db493f7711cf11a64b

Formatting of Table of contents has been fixed
Some of the items in Non-Functional requirements have been removed
Some indeations problems and typos have been fixed

Following figures have been replaced with the higher quality ones:
- Use case model (Figure 9)
- Class diagram (Figure 18)
- Activity Diagram for main menu (Figure 20)
- Sequence diagram for New Game (Figure 21)
- Sequence diagram for Attacking an Enemy (Figure 23)
- Sequence Diagram of Earning Bonus (Figure 24)

@alonge 
@halilbulentorhon 
@ftaskale
